# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7d850bf4dfcc0bb008f9a968760aaac0b01d7e4411f71cc830acddf7c8fcbdb209fb84b0a3d9980596a16673844c18d2f04d573994c9fa0499ab8b25e04c4d2c

test:
  secret_key_base: 9d7b7003a3126f75edab5e90de48fff56eacfe858b97b4bf8875baf816d9d930358f82d1d0b1f3d4e264cda91735003577fa481a011d319aac91bb867cb13d4a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
